name: Lint
on: pull_request
jobs:
  check:
    name: ESLint
    runs-on: ubuntu-latest
    concurrency:
      group: checks-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: pnpm install
      - run: pnpm lint
